services:
    php-apache:
        container_name: phpgridserver
        image: phpgridserver:0.1
        hostname: phpgridserver
        networks:
            - test-net
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www
        environment:
            SERVER_NAME: akitest.dyndns.info
        ports:
            - 8020:80
    db:
        container_name: db
        image: mariadb:latest
        restart: always
        hostname: db
        networks:
            - test-net
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: mvnrw07
            MARIADB_DATABASE: phpgridserver
            MARIADB_USER: phpgridserver
            MARIADB_PASSWORD: phpgridserver
        ports:
            - 9306:3306
networks:
    test-net:
