; This is the main configuration file for an instance of OpenSim running in dereos.org grid
;
[DatabaseService]
    Type="MySQL"
	; StorageProvider="OpenSim.Data.MySQL.dll"
    StorageProvider="OpenSim.Data.MySQL.dll"
    ConnectionString = "Data Source=localhost;Port=9306;Database=aki_kosuai;User ID=opensim;Password=mvnrw07;Old Guids=true;SslMode=None;"	
[AssetService]
DefaultAssetLoader="OpenSim.Framework.AssetLoader.Filesystem.dll"
AssetLoaderArgs="assets/AssetSets.xml"

[HGFriendsModule]

    ; User level required to be able to send friendship invitations to foreign users
    ;LevelHGFriends = 0;
[Modules]
AssetCaching="FlotsamAssetCache"
Include-FlotsamCache="config-include/FlotsamCache.ini"

[AuthorizationService]

    ; If you have regions with access restrictions
    ; specify them here using the convention
    ; Region_<Region_Name> = <flags>
    ; Valid flags are:
    ; DisallowForeigners -- HG visitors not allowed
    ; DisallowResidents -- only Admins and Managers allowed
    ; Example:
    ; Region_Test_1 = "DisallowForeigners"

[MuteListService]
    MuteListServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[AgentPreferencesService]
    ;
    ; Change this to your grid-wide avatar prefs server
    ;
    AgentPreferencesServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

	
[phpRobust]
Include-phpRobust="http://akitest.dyndns.info:8020/sim_grid_info?config_type=opensim-nini-coreprofile"
