; This is the main configuration file for an instance of OpenSim running in grid mode

[DatabaseService]
Type="MySQL"
StorageProvider="OpenSim.Data.MySQL.dll"
; use in grid 
; ConnectionString="Data Source=localhost;Database=dereos_kosuai;User ID=opensim;Password=M+rfkbwr;"
; use for local development
ConnectionString="Data Source=localhost;Port=9306;Database=dereos_kosuai;User ID=opensim;Password=K5yqk3LSCpmFTWJ9QHPE2r;Old Guids=true;SslMode=None;"

[Hypergrid]
    ; Uncomment the variables in this section only if you are in
    ; Hypergrid configuration. Otherwise, ignore.

    ;# {HomeURI} {Hypergrid} {The Home URL of this world} {}
    ;; If this is a standalone world, this is the address of this instance.
    ;; If this is a grided simulator, this is the address of the external robust server that
    ;; runs the UserAgentsService.
    ;; For example http://myworld.com:9000 or http://myworld.com:8002
    ;; This is a default that can be overwritten in some sections.
    HomeURI = "${Const|PrivURL}:${Const|PrivatePort}/"
	
    ;# {GatekeeperURI} {Hypergrid} {The URL of the gatekeeper of this world} {}
    ;; If this is a standalone world, this is the address of this instance.
    ;; If this is a grided simulator, this is the address of the external robust server
    ;; that runs the Gatekeeper service.
    ;; For example http://myworld.com:9000 or http://myworld.com:8002
    ;; This is a default that can be overwritten in some sections.
    GatekeeperURI = "${Const|PrivURL}:${Const|PrivatePort}/"


[Modules]
    AssetCaching = "FlotsamAssetCache"
    Include-FlotsamCache = "config-include/FlotsamCache.ini"


[AssetService]
    DefaultAssetLoader = "OpenSim.Framework.AssetLoader.Filesystem.dll"
    AssetLoaderArgs = "assets/AssetSets.xml"

    AssetServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[InventoryService]
    InventoryServerURI = "${Const|PrivURL}:${Const|PrivatePort}"
    MaxRetries = 3

[GridInfo]
   GridInfoURI = "http://dereos.org/"

[GridService]
    GridServerURI = "${Const|PrivURL}:${Const|PrivatePort}"
    MapTileDirectory = "./maptiles"
    ; === HG ONLY ===
    ;; Change this to the address of your Gatekeeper service
    ;; (usually bundled with the rest of the services in one
    ;; Robust server in port ${Const|PublicPort}, but not always)
    HypergridLinker = true
    AllowHypergridMapSearch = true
    Gatekeeper = "${Const|PrivURL}:${Const|PrivatePort}/"

[Messaging]
    OfflineMessageModule = "Offline Message Module V2"    
    OfflineMessageURL = "${Const|PrivURL}:${Const|PrivatePort}"
    MuteListModule = "MuteListModule"
    MuteListURL = "${Const|PrivURL}:${Const|PrivatePort}"
    Gatekeeper = "${Const|PrivURL}:${Const|PrivatePort}/"

[AvatarService]
    AvatarServerURI="${Const|PrivURL}:${Const|PrivatePort}"

[AgentPreferencesService]
    ;
    ; Change this to your grid-wide avatar prefs server
    ;
    AgentPreferencesServerURI="${Const|PrivURL}:${Const|PrivatePort}"

[PresenceService]
    ;
    ; Change this to your grid-wide presence server
    ;
    PresenceServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[UserAccountService]
    ;
    ; Change this to your grid-wide user accounts server
    ;
    UserAccountServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[GridUserService]
    ;
    ; Change this to your grid-wide user accounts server
    ;
    GridUserServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[AuthenticationService]
    ;
    ; Change this to your grid-wide authentication server
    ;
    AuthenticationServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[FriendsService]
    ;
    ; Change this to your grid-wide friends server
    ;
    FriendsServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[HGInventoryAccessModule]
    ;
    ; === HG ONLY ===
    ; Change this to your server
    ; accessible from other grids
    ;
    HomeURI = "${Const|PrivURL}:${Const|PrivatePort}/"
    Gatekeeper = "${Const|PrivURL}:${Const|PrivatePort}/"
    ;; If you want to protect your assets from being copied by foreign visitors
    ;; set this to false. You may want to do this on sims that have licensed content.
    ;; Default is true.
    OutboundPermission = True

    ;; Send visual reminder to local users that their inventories are unavailable while they are traveling
    ;; and available when they return. True by default.
    RestrictInventoryAccessAbroad = false


[HGAssetService]
    ;
    ; === HG ONLY ===
    ; Change this to your server
    ; accessible from other grids
    ;
    HomeURI = "${Const|PrivURL}:${Const|PrivatePort}/"

    ;; The asset types that this grid can export to / import from other grids.
    ;; Comma separated.
    ;; Valid values are all the asset types in OpenMetaverse.AssetType, namely:
    ;; Unknown, Texture, Sound, CallingCard, Landmark, Clothing, Object, Notecard, LSLText,
    ;; LSLBytecode, TextureTGA, Bodypart, SoundWAV, ImageTGA, ImageJPEG, Animation, Gesture, Mesh
    ;;
    ;; Leave blank or commented if you don't want to apply any restrictions.
    ;; A more strict, but still reasonable, policy may be to disallow the exchange
    ;; of scripts, like so:
    ; DisallowExport ="LSLText"
    ; DisallowImport ="LSLBytecode"

[HGFriendsModule]
    ; User level required to be able to send friendship invitations to foreign users
    ;LevelHGFriends = 0;

[UserAgentService]
    ;
    ; === HG ONLY ===
    ; Change this to your user agent server (HG robust)
    ;
    UserAgentServerURI = "${Const|PrivURL}:${Const|PrivatePort}/"

[Groups]
    Enabled = true
    Module = "Groups Module V2"
    ServicesConnectorModule = "Groups HG Service Connector"
    LocalService = remote
    GroupsServerURI = "${Const|PrivURL}:${Const|PrivatePort}"
    HomeURI = "${Const|PrivURL}:${Const|PrivatePort}/"
    MessagingEnabled = true
    MessagingModule = "Groups Messaging Module V2"
    MessageOnlineUsersOnly = true

[Profile]


[MapImageService]
    MapImageServerURI = "${Const|PrivURL}:${Const|PrivatePort}"

[AuthorizationService]
    ; If you have regions with access restrictions
    ; specify them here using the convention
    ; Region_<Region_Name> = <flags>
    ; Valid flags are:
    ; DisallowForeigners -- HG visitors not allowed
    ; DisallowResidents -- only Admins and Managers allowed
    ; Example:
    ; Region_Test_1 = "DisallowForeigners"

[MuteListService]
    MuteListServerURI="${Const|PrivURL}:${Const|PrivatePort}"

[DataSnapshot]
    index_sims = true
    data_exposure = minimum
    gridname = "dereosgrid"
    data_services="${Const|PrivURL}:${Const|PrivatePort}/search/register.php"

[AgentPreferencesService]
    AgentPreferencesServerURI="${Const|PrivURL}:${Const|PrivatePort}"
    
[SimulatorFeatures]
    MapTileURL="${Const|PrivURL}/map/"
    SearchServerURI = "${Const|PrivURL}:${Const|PrivatePort}/"
