[Ko Suai]
RegionUUID = "2547e7a0-a7eb-11e4-bcd8-0800200c9a66"
;Location = "9199,10100"        ; debug
Location = "9999,10000"          ; original
InternalAddress = "0.0.0.0"
InternalPort = 8021
AllowAlternatePorts = False
ExternalHostName = "akitest.dyndns.info"
MasterAvatarFirstName = "Akira"
MasterAvatarLastName = "Sonoda"
ClampPrimSize = False
MaxPrims = 15000

